name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile
        run: |
          make
        env:
          CC: gcc
  build-linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile
        run: |
          make
        env:
          CC: clang
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile
        run: |
          make
        env:
          CC: clang
  build-windows-msvc:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
        - uses: seanmiddleditch/gha-setup-vsdevenv@master
        - name: compile
          shell: cmd
          run: |
            ./build_msvc.bat
