name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: compile
        run: |
          make c_doodles_gcc
        env:
          CC: gcc
  build-linux-clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: compile
        run: |
          make c_doodles_clang
        env:
          CC: clang
  build-macos-clang:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile
        run: |
          make c_doodles_clang
        env:
          CC: clang
  build-windows-msvc:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
        - uses: seanmiddleditch/gha-setup-vsdevenv@master
        - name: compile
          shell: cmd
          run: |
            ./build_msvc.bat
  build-freebsd-clang:
    runs-on: macos-latest
    name: FreeBSD Clang
    steps:
      - uses: actions/checkout@v2
      - name: FreeBSD
        id: build
        uses: vmactions/freebsd-vm@v0.0.9
        with:
          usesh: true
          prepare: pkg install -y pkgconf gmake
          run: |
            freebsd-version
            gmake c_doodles_clang
